name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/distributed-rate-limiter
            # 1. Take ownership back from Docker so Git doesn't get "Permission Denied"
            sudo chown -R ubuntu:ubuntu .
            # 2. Force Git to wipe away any files Grafana modified
            git reset --hard origin/main
            git clean -fd
            git pull origin main
            # 3. Give the monitoring folder back to Grafana (User ID 472)
            sudo chown -R 472:472 monitoring/
            sudo docker compose up -d --build